packages:
  - packages/*

catalog:
  '@electron-toolkit/tsconfig': ^2.0.0
  '@types/node': ^25.5.0
  '@typescript/native-preview': 7.0.0-dev.20260314.1
  '@vueuse/core': ^14.2.1
  electron: ^41.0.2
  electron-vite: ^5.0.0
  zod-electron-store: ^2.0.2
  es-toolkit: ^1.45.1
  mitt: ^3.0.1
  tsdown: ^0.21.2
  vite: ^8.0.0
  vue: ^3.5.30
